project:
  type: website

website:
  title: "BINF301 Genome-scale Algorithms"
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - julia-intro.qmd
      - section: "Cluster analysis"
        contents:
          - cluster-analysis/cancer-subtypes.qmd
          - cluster-analysis/combinatorial-clustering.qmd
      - section: "Regularized regression"
      - section: "Dimensionality reduction"
      - section: "Causal inference"
      - section: "Graphical models"
      - section: "Spatio-Temporal models"
      - section: "Appendix"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto




