project:
  type: website

website:
  title: "BINF301 Machine Learning for Systems Biology"
  reader-mode: true
  page-navigation: true
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - julia-intro.qmd
      - section: "Cluster analysis"
        contents:
          - cluster-analysis/cancer-subtypes.qmd
          - cluster-analysis/combinatorial-clustering.qmd
          - cluster-analysis/mixture-distributions.qmd
      - section: "Statistical significance"
        contents:
          - statistical-significance/statistical-significance-gws.qmd
          - statistical-significance/fdr-estimation.qmd
      - section: "Regularized regression"
        contents:
          - regularized-regression/drug-sensitivity.qmd
          - regularized-regression/ridge-lasso-elnet.qmd
      - section: "Dimensionality reduction"
        contents:
          - dimensionality-reduction/pca.qmd
          - dimensionality-reduction/tsne-umap.qmd
      - section: "Causal inference"
        contents:
          - causal-inference/causal-assoc-genes-disease.qmd
          - causal-inference/mediation-iv.qmd
          - causal-inference/causal-model-selection.qmd
      - section: "Graphical models"
        contents:
          - graphical-models/gene-regulatory-networks.qmd
          - graphical-models/bayesian-networks.qmd
      - section: "Gaussian processes"
        contents:
          - gaussian-processes/variance-components-genomics.qmd
          - gaussian-processes/gaussian-processes.qmd
      - section: "Neural networks"
        contents:
          - neural-networks/protein-structure-prediction.qmd
          - neural-networks/neural-networks.qmd
      - section: "Appendix"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto




