project:
  type: website

website:
  title: "BINF301 Machine Learning for Systems Biology"
  reader-mode: true
  page-navigation: true
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - julia-intro.qmd
      - section: "Cluster analysis"
        contents:
          - href: cluster-analysis/cancer-subtypes.qmd
            text: Path-breaking paper
          - href: cluster-analysis/combinatorial-clustering.qmd
            text: Theory
          - href: cluster-analysis/cluster-analysis-notebook.qmd
            text: Implementation
      - section: "Statistical significance"
        contents:
          - href: statistical-significance/statistical-significance-gws.qmd
            text: Path-breaking paper
          - href: statistical-significance/fdr-estimation.qmd
            text: Theory
          - href: statistical-significance/statistical-significance-notebook.qmd
            text: Implementation
      - section: "Regularized regression"
        contents:
          - href: regularized-regression/drug-sensitivity.qmd
            text: Path-breaking paper
          - href: regularized-regression/ridge-lasso-elnet.qmd
            text: Theory
          - href: regularized-regression/regularized-regression-notebook.qmd
            text: Implementation
      - section: "Dimensionality reduction"
        contents:
          - href: dimensionality-reduction/brain-cell-types.qmd
            text: Path-breaking paper
          - href: dimensionality-reduction/pca.qmd
            text: Theory (PCA)
          - href: dimensionality-reduction/tsne-umap.qmd
            text: Theory (t-SNE, UMAP)
          - href: dimensionality-reduction/dimensionality-reduction-notebook.qmd
            text: Implementation
      - section: "Causal inference"
        contents:
          - href: causal-inference/causal-assoc-genes-disease.qmd
            text: Path-breaking paper
          - href: causal-inference/mediation-iv.qmd
            text: Theory
          - href: causal-inference/causal-inference-notebook.qmd
            text: Implementation
      - section: "Bayesian networks"
        contents:
          - href: bayesian-networks/gene-regulatory-networks.qmd
            text: Path-breaking paper
          - href: bayesian-networks/bayesian-networks.qmd
            text: Theory
      - section: "Gaussian processes"
        contents:
          - href: gaussian-processes/variance-components-genomics.qmd
            text: Path-breaking paper
          - href: gaussian-processes/gaussian-processes.qmd
            text: Theory
          - href: gaussian-processes/gaussian-processes-notebook.qmd
            text: Implementation
      - section: "Neural networks"
        contents:
          - href: neural-networks/protein-structure-prediction.qmd
            text: Path-breaking paper
          - href: neural-networks/neural-networks.qmd
            text: Theory
      - section: "Appendix"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto




