---
title: "Spatial gene experssion"
page-layout: full
title-block-banner: false
---

## Path-breaking paper: Efficient Control of Population Structure in Model Organism Association Mapping

::: {.callout-tip}
## Path-breaking paper

Kang HM, et al. [*Efficient Control of Population Structure in Model Organism Association Mapping*](https://doi.org/10.1534/genetics.107.080101), Genetics 178(3):1709–1723 (2008)
:::


## Test of time

Population structure:

::: {.callout-tip}
## Test of time paper

- Canela-Xandri O, Rawlik K & Tenesa A. [*An atlas of genetic associations in UK Biobank*](https://doi.org/10.1038/s41588-018-0248-z). Nat Genet 50, 1593–1599 (2018). 
- Loh PR,  et al. [*Mixed-model association for biobank-scale datasets*](https://doi.org/10.1038/s41588-018-0144-6). Nat Genet 50, 906–908 (2018). 
:::


Single-cell RNA-seq:

::: {.callout-tip}
## Test of time paper

Buettner F, et al. [*Computational analysis of cell-to-cell heterogeneity in single-cell RNA-sequencing data reveals hidden subpopulations of cells*](https://doi.org/10.1038/nbt.3102). Nat Biotechnol 33, 155–160 (2015). 
:::

Spatial transcriptomics:

::: {.callout-tip}
## Test of time paper

Arnol, et al. [*Modeling Cell-Cell Interactions from Spatial Molecular Data with Spatial Variance Component Analysis.*](https://doi.org/10.1016/j.celrep.2019.08.077) Cell Reports 29:202 (2019).
:::
